application: navpage
version: 1
runtime: python
api_version: 1

handlers:
  - url: /
    script: home.py

  - url: /index\.html
    script: home.py
    
  - url: /t/.*
    script: category.py
    
  - url: /(.*\.(gif|png|jpg|css|js))
    static_files: static/\1
    upload: static/(.*\.(gif|png|jpg|css|js))
    
  - url: /admin/.*
    script: admin.py
    login: admin
    
  - url: /.*
    script: not_found.py